id: I3B53050B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T12:43:25+00:00'
last_modified: '2022-06-08T13:39:11.774094+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24741
  title: བསྡུས་གྲྭའི་དོགས་དཔྱོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    BB55:
      image_group_id: I1KG24743
      title: ''
      total_pages: 314
      order: 1
      base_file: BB55.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
