id: P010444
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24741
  title: བསྡུས་གྲྭའི་དོགས་དཔྱོད།
  author: ''
  volumes:
    4e97b81432014676ae3e41c40fde0298:
      image_group_id: I1KG24743
      title: ''
      volume_number: 1
      total_pages: 314
